controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home_page:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: home/index.html.twig

sales_page:
    path: /sales
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: sale/index.html.twig
        context:
            sales: []

roysched_page:
    path: /roysched
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: roysched/index.html.twig
        context:
            royscheds: []

jobs_page:
    path: /jobs
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: job/index.html.twig
        context:
            jobs: []

pub_info_page:
    path: /pub-info
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: pub_info/index.html.twig
        context:
            pub_infos: []

employees_page:
    path: /employees
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: employee/index.html.twig
        context:
            employees: []
